# Workflow
# Should Have Name

name : hello workflow

on :
    workflow_dispatch:
# Jobs
# Should be inside the workflow

jobs:
    say-hello:
        runs-on: ubuntu-latest 
        steps:
                - name: Say hello to new users
                  run: echo "hello dosto"
        
        

# Steps
# Should be insite the job

# Actions
# Should be inside the Steps


  

                 
